package timaxa007.activate_block;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import cpw.mods.fml.relauncher.Side;
import timaxa007.activate_block.network.BlockActivatedMessage;

@Mod(modid = OpenDoorFMod.MODID, name = OpenDoorFMod.NAME, version = OpenDoorFMod.VERSION)
public class OpenDoorFMod {

	public static final String
	MODID = "activate_block",
	NAME = "Activate Block Mod",
	VERSION = "0.5.3";

	@Mod.Instance(MODID)
	public static OpenDoorFMod instance;

	@Mod.Metadata(MODID)
	public static ModMetadata metadata;

	@SidedProxy(modId = MODID, serverSide = "timaxa007.activate_block.Proxy", clientSide = "timaxa007.activate_block.client.Proxy")
	public static Proxy proxy;

	public static final SimpleNetworkWrapper network = NetworkRegistry.INSTANCE.newSimpleChannel(MODID);

	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		network.registerMessage(BlockActivatedMessage.Handler.class, BlockActivatedMessage.class, 0, Side.CLIENT);
		network.registerMessage(BlockActivatedMessage.Handler.class, BlockActivatedMessage.class, 0, Side.SERVER);
		proxy.preInit(event);
	}

	private ModMetadata metadata(ModMetadata metadata) {
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.modId = MODID;
		metadata.name = NAME;
		metadata.version = VERSION;
		metadata.autogenerated = false;
		return metadata;
	}

}
